import dns from "node:dns";
dns.setServers(['8.8.8.8','8.8.4.4']);

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Footer from "./components/shared/Footer";
import Navbar from "./components/shared/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SunCart – Summer Essentials Store",
  description: "Generated by create next app",
   icons: {
    icon: "/favicon.jpg", 
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      dara-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}

    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Footer />
         <Toaster
          position="top-center"
          reverseOrder={false}
        />

      </body>
    </html>
  );
}
